apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  interval: 1m
  chart:
    spec:
      chart: mosquitto
      version: "2.0.7"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 60m
  values:
    persistence:
      data:
        # HA stores auth data in .storage/auth in the config folder
        enabled: true
        storageClass: nfs-client
        size: "1Gi"
