apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 4.8.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 60m
  values:
    persistence:
      data:
        # HA stores auth data in .storage/auth in the config folder
        enabled: true
        storageClass: nfs-client
        accessMode: ReadWriteOnce
        size: "1Gi"
    service:
      main:
        # This needs to be accessible from outside the cluster so IoT components
        # can speak to it.
        type: NodePort
