---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd2
  namespace: linkerd
spec:
  interval: 60m
  chart:
    spec:
      chart: linkerd2
      version: "2.10.0"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      interval: 60m
