apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://helm.twun.io
      chart: docker-registry
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system
      interval: 1m
  values:
    persistence:
      enabled: true
      size: 50Gi
      storageClass: nfs-client
    ingress:
      enabled: true
      hosts:
      - k8s.home
      path: /docker-registry
      annotations:
        traefik.ingress.kubernetes.io/rewrite-target: /
