---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cockroachdb-operator
  namespace: cockroachdb
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://charts.cockroachdb.com
      chart: cockroachdb
      version: 21.2.0
      sourceRef:
        kind: HelmRepository
        name: cockroachdb
        namespace: flux-system
      interval: 10m

