---
kind: ConfigMap
apiVersion: v1
metadata:
  name: home-assistant-config
  namespace: home-assistant
data:
  configuration.yaml: |
    # Configure a default setup of Home Assistant (frontend, api, etc)
    default_config: {}

    # Text to speech
    tts:
    - platform: google_translate

    # group: !include groups.yaml
    # automation: !include automations.yaml
    # script: !include scripts.yaml
    # scene: !include scenes.yaml

    recorder:
      db_url: postgresql://home-assistant:home-assistant-pass@home-assistant-postgresql/home-assistant

    plant:
      banana_plant:
        sensors:
          moisture: sensor.banana_plant_moisture
          battery: sensor.banana_plant_battery
          temperature: sensor.banana_plant_temperature
          conductivity: sensor.banana_plant_conductivity
          brightness: sensor.banana_plant_brightness
        min_moisture: 20
        max_moisture: 60
        min_battery: 17
        min_conductivity: 500
        min_temperature: 15

    sensor:
    - platform: mqtt
      name: banana_plant_moisture
      state_topic: banana_plant_topic
      value_template: "{{ value_json.moisture | int }}"
      unit_of_measurement: "%"
    - platform: mqtt
      name: banana_plant_battery
      state_topic: banana_plant_topic
      value_template: "{{ value_json.battery | int }}"
      unit_of_measurement: "%"
    - platform: mqtt
      name: banana_plant_temperature
      state_topic: banana_plant_topic
      value_template: "{{ value_json.temperature | float }}"
      unit_of_measurement: "°C"
    - platform: mqtt
      name: banana_plant_conductivity
      state_topic: banana_plant_topic
      value_template: "{{ value_json.conductivity | int }}"
      unit_of_measurement: "µS/cm"
    - platform: mqtt
      name: banana_plant_brightness
      state_topic: banana_plant_topic
      value_template: "{{ value_json.brightness | int }}"
      unit_of_measurement: "Lux"
   
