---
kind: ConfigMap
apiVersion: v1
metadata:
  name: home-assistant-config
  namespace: home-assistant
data:
  configuration.yaml: |
    # Configure a default setup of Home Assistant (frontend, api, etc)
    default_config: {}

    # Text to speech
    tts:
    - platform: google_translate

    # group: !include groups.yaml
    automation: !include automations.yaml
    # script: !include scripts.yaml
    # scene: !include scenes.yaml

    # Use postgres to record historic data
    # https://www.home-assistant.io/integrations/recorder/
    recorder:
      db_url: postgresql://home-assistant:home-assistant-pass@home-assistant-postgresql/home-assistant

    # MiFlora plant sensors
    # https://www.home-assistant.io/integrations/plant/
    plant:
      banana_plant:
        sensors:
          moisture: sensor.banana_plant_moisture
          battery: sensor.banana_plant_battery
          temperature: sensor.banana_plant_temperature
          conductivity: sensor.banana_plant_conductivity
          brightness: sensor.banana_plant_brightness
        min_moisture: 20
        max_moisture: 60
        min_battery: 17
        min_conductivity: 500
        min_temperature: 15

    # I run an MQTT broker in Kubernetes for the MiFlora plant sensor devices
    # https://www.home-assistant.io/integrations/mqtt/
    mqtt:
      broker: mosquitto.mosquitto.svc.cluster.local

    # https://www.home-assistant.io/integrations/tplink/
    tplink:
      switch:
      - host: 192.168.1.235 # Comms cabinet
      - host: 192.168.3.20 # Washing machine

    # Define some sensors manually
    # https://www.home-assistant.io/integrations/sensor
    sensor:
    - platform: mqtt
      name: banana_plant_moisture
      state_topic: homeassistant/sensor/test2/state
      value_template: "{{ value_json.moisture | int }}"
      unit_of_measurement: "%"
    - platform: mqtt
      name: banana_plant_battery
      state_topic: homeassistant/sensor/test2/state
      value_template: "{{ value_json.battery | int }}"
      unit_of_measurement: "%"
    - platform: mqtt
      name: banana_plant_temperature
      state_topic: homeassistant/sensor/test2/state
      value_template: "{{ value_json.temperature | float }}"
      unit_of_measurement: "°C"
    - platform: mqtt
      name: banana_plant_conductivity
      state_topic: homeassistant/sensor/test2/state
      value_template: "{{ value_json.conductivity | int }}"
      unit_of_measurement: "µS/cm"
    - platform: mqtt
      name: banana_plant_brightness
      state_topic: homeassistant/sensor/test2/state
      value_template: "{{ value_json.light | int }}"
      unit_of_measurement: "Lux"
    - platform: template
      sensors:
        comms_switch_amps:
          friendly_name_template: "{{ state_attr('switch.comms_switch','friendly_name') }} Current"
          value_template: "{{ state_attr('switch.comms_switch','current_a') }}"
          unit_of_measurement: "A"
        comms_switch_watts:
          friendly_name_template: "{{ state_attr('switch.comms_switch','friendly_name') }} Current Consumption"
          value_template: "{{ state_attr('switch.comms_switch','current_power_w') }}"
          unit_of_measurement: "W"
        comms_switch_total_kwh:
          friendly_name_template: "{{ state_attr('switch.comms_switch','friendly_name') }} Total Consumption"
          value_template: "{{ state_attr('switch.comms_switch','total_energy_kwh') }}"
          unit_of_measurement: "kWh"
        comms_switch_volts:
          friendly_name_template: "{{ state_attr('switch.comms_switch','friendly_name') }} Voltage"
          value_template: "{{ state_attr('switch.comms_switch','voltage') }}"
          unit_of_measurement: "V"
        comms_switch_today_kwh:
          friendly_name_template: "{{ state_attr('switch.comms_switch','friendly_name') }} Today's Consumption"
          value_template: "{{ state_attr('switch.comms_switch','today_energy_kwh') }}"
          unit_of_measurement: "kWh"
    - platform: template
      sensors:
        washing_machine_amps:
          friendly_name_template: "{{ state_attr('switch.washing_machine','friendly_name') }} Current"
          value_template: "{{ state_attr('switch.washing_machine','current_a') }}"
          unit_of_measurement: "A"
        washing_machine_watts:
          friendly_name_template: "{{ state_attr('switch.washing_machine','friendly_name') }} Current Consumption"
          value_template: "{{ state_attr('switch.washing_machine','current_power_w') }}"
          unit_of_measurement: "W"
        washing_machine_total_kwh:
          friendly_name_template: "{{ state_attr('switch.washing_machine','friendly_name') }} Total Consumption"
          value_template: "{{ state_attr('switch.washing_machine','total_energy_kwh') }}"
          unit_of_measurement: "kWh"
        washing_machine_volts:
          friendly_name_template: "{{ state_attr('switch.washing_machine','friendly_name') }} Voltage"
          value_template: "{{ state_attr('switch.washing_machine','voltage') }}"
          unit_of_measurement: "V"
        washing_machine_today_kwh:
          friendly_name_template: "{{ state_attr('switch.washing_machine','friendly_name') }} Today's Consumption"
          value_template: "{{ state_attr('switch.washing_machine','today_energy_kwh') }}"
          unit_of_measurement: "kWh"
