---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: "7.2.1"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
    persistence:
      config:
        enabled: true
    postgresql:
      enabled: true
      persistence:
        enabled: true
      image:
        repository: postgres
        tag: 13.2
    prometheus:
      serviceMonitor:
        enabled: true
