---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 1m
  chart:
    spec:
      chart: home-assistant
      version: "9.3.0"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  values:
    image:
      tag: "2021.7.4"
    ingress:
      main:
        enabled: true
        hosts:
        - host: home-assistant.home
          paths:
          - path: "/"
    additionalVolumes:
      - name: config-volume
        configMap:
          name: home-assistant-config
    additionalVolumeMounts:
      - name: config-volume
        mountPath: /config/configuration.yaml
        subPath: configuration.yaml
    persistence:
      config:
        enabled: true
        storageClass: nfs-client
    prometheus:
      serviceMonitor:
        enabled: true
