---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://pajikos.github.io/home-assistant-helm-chart/
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: pajikos
        namespace: flux-system
      interval: 10m
  values:
    ingress:
      enabled: true
      annotations:
        nginx.org/websocket-services: home-assistant
      hosts:
      - host: home-assistant.home
        paths:
        - path: "/"
          pathType: ImplementationSpecific
    persistence:
      enabled: true
      storageClass: nfs-client
    serviceMonitor:
      enabled: true
