---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 1m
  chart:
    spec:
      chart: home-assistant
      version: "7.2.1"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 60m
  values:
    ingress:
      enabled: true
      hosts:
      - host: home-assistant.home
        paths:
        - path: "/"
    additionalVolumes:
      - name: config-volume
        configMap:
          name: home-assistant-config
    additionalVolumeMounts:
      - name: config-volume
        mountPath: /config/configuration.yaml
        subPath: configuration.yaml
    persistence:
      config:
        # HA stores auth data in .storage/auth in the config folder
        enabled: true
        storageClass: nfs-client
    postgresql:
      enabled: true
      persistence:
        enabled: true
        storageClass: nfs-client
      image:
        repository: postgres
        tag: 13.2
    prometheus:
      serviceMonitor:
        enabled: true
