apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: home-email
  labels:
    alertmanagerConfig: custom
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'email'
  receivers:
  - name: 'email'
    emailConfigs:
    - sendResolved: true
      to: martin+home-prometheus@mfoot.com
      smarthost: smtp.gmail.com:587
      authSecret:
        name: gmail-smtp
        key: password
      
