---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: storage
spec:
  interval: 1m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.6"
      interval: 60m
  values:
    nfs:
      server: 192.168.1.10
      path: /volume1/home-cluster-nfs
