---
- name: Install packages for my Kubernetes applications
  hosts: kubernetes
  become: true
  gather_facts: false
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nfs-common # For the provisioning volumes from my NAS
        - pi-bluetooth # For the BLE beacon and my Mi Flora devices
        - bluez
