apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-route53-credentials-secret
  namespace: cert-manager
spec:
  encryptedData:
    secret-access-key: AgAhFFWc4qM1EnmRLylvOfnqc1eGbrJKOgAUhSttljtw9wXjoZlxMKVBy7OwIwwBvcPxbv9Ek6aTpELaP0bOw/vBMiCRrp98t24YS3R6oivL0NdJ37xZ73XWm/szc97K+t/K+uhsnqkBJl6pLE/sS7xXwJgBAXnenD6WahyZja5VPY4urFO+O1KQifxkmafNSo5UwmOCNUGhxvZx1vQAFMU1or+U5KjNfQW835xk2/b/JAHEcHSwVGroYy0sWp+kE1Y6BloApYVEfwhkPNWqXfp54HGMMpRgbDEfiO5HnuWJJYJbSDtdgvwyqrrVUdTYt8WS6l5WqIKZCoNF3TYu1Sf9NB3oV8KYJ1Ama31NYCb4TF3XqeeP46j7Gar4dlaYwkaFsLFQeEAbujudtzhwkzzVB0IKAUOim0Ff++YatC+UAPpzbb18x+GnihTOvZvGzSqTi46y6pxTjUd6u+slXM8PKSweMvVGUjZ4mMyXZw0b5uKgQAlMlRPk1FUl+3ZeSsdNdVA00U+ss7t0YDvwg24tY6vO+/MGFF2xl+S6+gchjnkdcdBazSJ9Dl9Mf0/UI1pHMWAKUqeLeTzEMzg7IUeWNYNwdilOdBIyade/3KkV+T+l10SLanrGcK02zHBaQ7ZX2FjDnjnEAa18BfUNRxUho/z+WVHOTYEQYQ/TdRks/unptFg8qLG2HiTfBx+mgw5tGkYuYibLZ+Ju5bpGtAz6F7ryXQ4WFvW0IN9upW8m8yzE0a1jfuXp
  template:
    metadata:
      name: prod-route53-credentials-secret
      namespace: cert-manager

