apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-route53-credentials-secret
  namespace: cert-manager
spec:
  encryptedData:
    secret-access-key: AgCMs3XNUHJCpnO5nD2/zvcOIq+fZlmnq6GPjl4dH4SbXaU9Bu9dW3qP2GvVaU4Gglmg4wWMMAmsTIzYnwdOEUSJ5olYaLAcxHWxrwGOKqS2j45v8T+fS/NoF+VOUB3YG7lizl9aBeXDYOg0G5IHDBaZIl/Q0ZIwq2itYDrJ8sUN1qQci+4Bo9/9+a8a+XkuMGphEPM7vzJPca0OiEbhh7zaVYmQdGjfSt2n42/W29EshTEpO/Am761Qcz1oZm/2Rtspq05sxgBXtegzQlByG+cCLm/wyiYE8LvwOIOts0d7j6wUAvILGBSlNHaJAM13x7mess2pcxDjfGJpnbv4/MslB/qtzz1ighYCqjr2IZd5KQumVcLoggmncd/kWTY/eSn7k+e63qs9SZ9cCqGn6phM2IAjxNSRCPaFGsL5oWtFB+IiWsseYDa6DlurYUyz3UhVKMOT0MFvthHDe9zba6J+cFOVhLPEaKV0Xidnb/kcFEiMQmNSnk8p46ZAGvmFiNiEXhjnKZTzXqVYIPTtiFZbICi8FQCjXGiQr5J6vdM594uTJPU4iM4zjBdlWcKelq4407+6PBqXZ5nqtT/ObzUVuX+/LO0AzCDjojfwP92OQqBcbWxDT8F1NtfbGj5tMX6djdRgRey4pZuFf7TjC1LnJJiKw+XWDZFqgaTPaJYd5mKjZilMSA+FiBB18dQ1FJaGYLT5uO0hMfj0i5LLzTIQta9ZJ2G9kMJYRQTU2KnCIS+f/zCBGi6E
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prod-route53-credentials-secret
      namespace: cert-manager

