---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      version: 2.17.0
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      interval: 60m
