# See https://github.com/marketplace/actions/ansible-lint
name: Ansible Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v3
    - name: Lint Ansible Playbook
      uses: ansible-community/ansible-lint-action@v6.17.0
      with:
        path: "ansible/site.yml"
