name: Ansible Lint
on: [push, pull_request]
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible-lint ansible

    - name: Run ansible-lint
      run: |
        ansible-lint ansible/site.yml
