name: Renovate Helm Bot

on:
  schedule:
  - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Renovate Helm Releases
        uses: k8s-at-home/renovate-helm-releases@v1.4.5
        with:
          cluster-path: clusters/home-cluster

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Tag helmreleases with renovatebot annotations
          title: '[Renovate] Tag helmrelease(s)'
          body: >
            New annotations have been added to helmrelease objects. This allows renovatebot to pick them up and start providing updates.
          labels: automated
