name: Renovate Helm Bot

on:
  schedule:
  - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Renovate Helm Releases
        uses: k8s-at-home/renovate-helm-releases@v1.3.0
        with:
          cluster-path: clusters/home-cluster
