---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.27.0
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
      interval: 10m
  values:
    configuration:
      provider: aws
      
