---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 7.2.2
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 10m
  values:
    configuration:
      backupStorageLocation:
        - provider: aws
          bucket: home-kubernetes-cluster-backup
      volumeSnapshotLocation:
        - provider: aws
    credentials:
      existingSecret: velero-credentials
    schedules:
      cluster-backup:
        useOwnerReferencesInBackup: false
        schedule: "0 0 * * 1" # Monday at 00:00
        template:
            ttl: "336h" # 14 days
            storageLocation: aws
    upgradeCRDs: true
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.6.1
      volumeMounts:
      - mountPath: /target
        name: plugins
