apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    credentials-velero: AgCwOXxfnLyAwXNJgBbFxk/eDcB3BJR2Xi2GuRJWRNuBoR3k6HtmviUIEBh2m9Ukow5dByM2Stjp9f+GoWpodv3ZZFG9S8KANuc8l5XwVO0ZSbbVhBKeCMcMMhrFydvZ5Lbt8f4gjaXJ/dXUmxLcYrjVjIQldzDG59K2N921YC9sFq3czzk2+hM1RIdt50irkwc0Py2HuThhXc1K5mkpvnH4MjEPN3k1sS9RW+Zg6kxwFHBKSXMhRMOOUanwZKWhZuMcX1MHaTPaKswwqE3+/2Vk6c9tJVd8bfF37/3e3dOBkUyXM6PpO04Ca/iSST6fJn5QLNeIiw4om7znzstsFB6yVhd3MVaefa15UeMPWSmcMjOPzrNTnOzIkN6/oz0eFwOeU6FLqH/a3lN7mIWMez0gNYx5ku7MzN9lD1pOYRyFLejpzGGSaHUx7xWX0eAVZ0+16uu8FNCBz2MvIZJ33HGAzLgfYb99RvpIhG31jm9kcWeYQqbn0sw6yuah4NC45K1AGM17CuySMGjkTE4NGYBc8ROVACHcP3QtRCy2iqGZPVVZD3AcKyC9xiykkuSBeLDQCoQefIKF4CiQeG/gKCWIvSikDQUFeeAAkVQQdlMPMpaNZJ+nP8Q/GNag2zevbKEBvWlzSCEaKxl+LEzXSQnLnTAQZH7xlaE1LQaPjYfVjassG12ni5C1E+miNeWZL8u1y8KWNVoH+t0JT0sks3VrDVwXIbNbPTyfkTuNAYuS8HIF2iuGgPIlVmYeVO9EhKuhspDdEJnaMu71bS5NeOxH1LpbeL1ljHcN4hJrGKOPuoKBg+GCoPm5EnOdZB54is2psZXYGciMUi0XI6PzfMUN
  template:
    metadata:
      creationTimestamp: null
      name: velero-credentials
      namespace: velero

