apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgA/Ri1H/KLPa+JIUzWBZsPH5HMWsp9jRFLGQhoO+RikGSpJBbBlFQHs8vIWfu8rLRBs2WgJsst2wSBjro+qBEBaCFIDrtMCHdAGEO07qGmYRfF/B+XCQ3GOSR6Kp8JolxhsyhMHYyQ2jxgFcWM8GeAWWioydwQV+sOCiOYsO1MFpJiDjukQ86UwBxh7k2nFhG1pvqqMY2ESwswOTmiHq6UopfHCB4QNqJlrZS4TCLk/7ZUWjES3QYhwnPoPPL9Wp7Mar9+WT4MGSkKEo9F1hNqjrqfELf0RRf1YNq1wuOg14HYums/rD1SgLjNrM92AGaxWurwC75bwKqyb9WdmRoGOek+Lz9ZJnE2yjyjGLW4c6wGMwemujOydu5BPCLN+tNj0lxCGr6VGWleeNQ25roAnJyNlGC0Aw8USBADT9+Pe/cJ41kSdI5CPY/sv9mP32WX573sLT4zmfeQnH8uAfTlZYI+40FU+UbAFl5bfXGSKIgU1LPw00LO70mlnvYz5DE2xlrFoRt7N1VPD5dEwkgVRe+Wmk+jESnJRCF55PCMJrUjxPDuoHYRC0q5hNyFqHSwQuMHMZu+3QgpLJL7s5/XDMTgQZ7/UuGYVfvUhtyoYpEoiwvT5mCZ46y51PmBmARlv6nx4kXsh1z9/c1BqPIcF3hsCe83kWiDRa6IKjZeSbmvBfyJLZL/Z1C5A7mbMuM91rs8Tx4pFIuPa3hQh02xaRr1PXP5iBZ+pUUc0tZDiXPxb3szlrR0WfvDWz+kuHfMfzyyAVrUa+fWUS7A3wjPH8O968YJRvjWRmKX/75X66s+EVwB/i8x8/3vMpkfxu4eCJf4sRPmMtzRO6jJ6haa6
  template:
    metadata:
      creationTimestamp: null
      name: velero-credentials
      namespace: velero

